name: Lee's Blog
pygments: true
port: 4000
markdown: rdiscount
safe: false
paginate: 5
paginate_path: "page:num"
url: http://xiaomingli007.github.com
description: 自己使用Jekyll搭建的托管在github上的个人技术博客

keywords: "technology, javascript, blogging, web development, programming, xiaomingli007,李小明"

image:
  source: uploads
  output: generated
  presets:
    centered:
      attr:
